@startuml SoundscapeReapyController-UML
set namespaceSeparator .
class "AmbisonicBINaural" as AudioPlugins.Sparta.AmbisonicBINaural {
  plugin_name : str
  rotation(yaw: float, pitch: float, roll: float)
}
class "AmbisonicDECoder" as AudioPlugins.Sparta.AmbisonicDECoder {
  plugin_name : str
}
class "AmbisonicENCoder" as AudioPlugins.Sparta.AmbisonicENCoder {
  Sources : int
  plugin_name : str
  SpeakerPositions(source_number, position)
  SpeakersPositions(sources_positions)
  setNumSources(numSources_val)
  setSpeakerAzim(source_number, azim_value)
  setSpeakerElevation(source_number, elevation_value)
}
class "AudioData" as jsonUtils.AudioData {
  ambisonic : bool
  fileName : str
  sound_id : str
  sound_name : str
}
class "AudioPluginController" as AudioPlugins.AudioPluginController {
  TrackFX
  plugin_name : str
  sliderVals : tuple
  setWet(wet: float)
}
class "AudiosData" as jsonUtils.AudiosData {
  AudiosInfo : list
  GetAudioFileInfo(id: str) -> AudioData
}
class "ControllerWorkspace" as TrackDiscJockey.ControllerWorkspace {
}
class "Echo" as AudioPlugins.SoundEffects.Echo {
  effectParamsList : dict
  plugin_name : str
  setApplyEcho(enabled: bool)
  setDecayRatio(ratio: float)
  setDelay(delay_ms: float)
  setDryMix(value: float)
  setWetMix(value: float)
  updateSoundEffectParams(params: list)
}
class "HighLowPassFilter" as AudioPlugins.SoundEffects.HighLowPassFilter {
  effectParamsList : dict
  plugin_name : str
  setApplyFilter(enabled: bool)
  setHighPassFreq(freq: float)
  setLowPassFreq(freq: float)
  updateSoundEffectParams(params: list)
}
class "MatrixConvReverb" as AudioPlugins.Sparta.MatrixConvReverb {
  plugin_name : str
}
class "MultiConvReverb" as AudioPlugins.Sparta.MultiConvReverb {
  plugin_name : str
}
class "Occlusion" as AudioPlugins.SoundEffects.Occlusion {
  effectParamsList : dict
  plugin_name : str
  setApplyOcclusion(enabled: bool)
  setFrequencyDependent(enabled: bool)
  setGeneralOcclusion(value: float)
  setHighFreq(value: float)
  setLowFreq(value: float)
  setMidFreq(value: float)
  updateSoundEffectParams(params: list)
}
class "PlayDelayMeasure" as Debug.PerformanceMonitoring.PlayDelayMeasure {
  clock_offset : int
  delays_file : str
  print_delay_message : bool
  save_to_file : bool
  measure_delay(timestamp)
  save_measure_to_file(delay_time)
  set_clock_offset(offset: int)
}
class "ReverbRIR" as AudioPlugins.SoundEffects.ReverbRIR {
  plugin_name : str
}
class "RiReverbs" as AudioPlugins.RiReverbs {
  effectParamsList : dict
  add_to_track(soundtrack: SoundTrack, params) -> 'RiReverbs'
  setApplyReverb(enabled: bool)
  setRirPreset(rir_preset: str)
  updateSoundEffectParams(params: list)
}
class "SoundEffect" as AudioPlugins.SoundEffect {
  effectParamsList : NoneType
  add_to_track(soundtrack, initial_params: list) -> 'SoundEffect'
  remove_from_track()
  {abstract}updateSoundEffectParams(params: list)
}
class "SoundTrack" as TrackDiscJockey.SoundTrack {
  AudioData
  AudioID
  SoundEffects : list
  SoundUUID : UUID
  Track
  VolumeGain : float
  ambiSourceIndex : NoneType, int
  ambisonic
  audio_duration_seconds
  currentVolumeDB : float
  delay : int
  distanceRadius : float
  loop : bool
  muteState : bool
  positionalRot : tuple
  deleteSoundEffect(soundFX: SoundEffect)
  mute()
  newSoundEffect(soundFX: SoundEffect)
  unmute()
}
class "SoundscapeReapyControllerConfig" as jsonUtils.SoundscapeReapyControllerConfig {
  AmbisonicDecoderPreset
  AmbisonicOrder : int
  BinauralRotationUpdate
  DecoderAmbisonicTrackName
  DecoderBinauralTrackName
  EncoderAmbisonicTrackName
  EncoderMonoAudioTrackName
  InvertAzimuth
  InvertElevation
  LogCommunications
  MaxInfiniteSoundscapeMinutesTime : int
  MeasureDelay
  MuteAmbisonicDecoder
  MuteBinauralDecoder
  ReapyTemplateProjectPath : str
  ReverbVolumeLevel : float
  ReverbWetValue : float
  SaveDelayMeasure
  SoundsLocation : str
  SoundscapeVRUnityCommunicationPort
  TrackChannels : int
  UseAmbisonicDecoderPreset
  config_json
}
class "SoundscapeVRCommunicationsService" as SoundscapeVRCommunications.SoundscapeVRCommunicationsService {
  is_connected
  disconnect()
  receiveRequest() -> str
  sendResponse(response: str)
  start()
  wait_for_connection()
}
class "TrackSoundscapeDJManager" as TrackDiscJockey.TrackSoundscapeDJManager {
  measure_delay
  CommandReceive(msg: str) -> str
}
class "jsonDealer" as jsonUtils.jsonDealer {
}
AudioPlugins.RiReverbs --|> AudioPlugins.SoundEffect
AudioPlugins.SoundEffect --|> AudioPlugins.AudioPluginController
AudioPlugins.SoundEffects.Echo --|> AudioPlugins.SoundEffect
AudioPlugins.SoundEffects.HighLowPassFilter --|> AudioPlugins.SoundEffect
AudioPlugins.SoundEffects.Occlusion --|> AudioPlugins.SoundEffect
AudioPlugins.SoundEffects.ReverbRIR --|> AudioPlugins.RiReverbs
AudioPlugins.Sparta.AmbisonicBINaural --|> AudioPlugins.AudioPluginController
AudioPlugins.Sparta.AmbisonicDECoder --|> AudioPlugins.AudioPluginController
AudioPlugins.Sparta.AmbisonicENCoder --|> AudioPlugins.AudioPluginController
AudioPlugins.Sparta.MatrixConvReverb --|> AudioPlugins.RiReverbs
AudioPlugins.Sparta.MultiConvReverb --|> AudioPlugins.RiReverbs
Debug.PerformanceMonitoring.PlayDelayMeasure --|> TrackDiscJockey.ControllerWorkspace
jsonUtils.AudiosData --|> jsonUtils.jsonDealer
jsonUtils.SoundscapeReapyControllerConfig --|> jsonUtils.jsonDealer
jsonUtils.jsonDealer --|> TrackDiscJockey.ControllerWorkspace
jsonUtils.AudioData --o TrackDiscJockey.SoundTrack : AudioData
class "SoundscapeVReapy" as SoundscapeVReapy <<module>> {
  project
  config
  communicator
  ReapyManager
  _end_soundscape_task
  DISCONNECT_END_SOUNDSCAPE_DELAY_MS
  _delayed_end_soundscape()
  ReapyInit()
  check_reaper_running()
  Reset()
  Exit(communicator)
  main()
}
SoundscapeVReapy ..> SoundscapeVRCommunications.SoundscapeVRCommunicationsService
SoundscapeVReapy ..> TrackDiscJockey.TrackSoundscapeDJManager
SoundscapeVReapy ..> jsonUtils.SoundscapeReapyControllerConfig
@enduml
